env:
  node: true
parser: 'babel-eslint'
extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
rules:
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
  "react/require-default-props": 0
  "react/forbid-prop-types": [0, { "forbid": [<string>] }]
  "react/no-danger": 0
  "jsx-a11y/no-static-element-interactions": 0
