env:
  node: true
  browser: true,
parser: 'babel-eslint'
extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
rules:
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
  "react/require-default-props": 0
  "react/forbid-prop-types": [0, { "forbid": [<string>] }]
  "react/no-danger": 0
  "jsx-a11y/no-static-element-interactions": 0
  "import/no-extraneous-dependencies": ["error", { "devDependencies": ["server/*.js", "webpack.*.js", "gulpfile.babel.js"] }]
  "no-console": ["error", { allow: ["warn", "error"] }]
  "func-names": ["error", "never"]
  "no-param-reassign": ["error", { "props": false }]
