env:
  node: true
parser: 'babel-eslint'
extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
rules:
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
  "react/require-default-props": 0
