options:
  merge-default-rules: false
files:
  include: 'src/assets/**/*.scss'
rules:
  # Extends
  extends-before-declarations: 2
  extends-before-mixins: 2
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  empty-line-between-blocks: 0
  one-declaration-per-line: 2
  single-line-per-selector: 0

  # Disallows
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 0
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 0
  no-transition-all: 2
  no-url-protocols: 2
  no-vendor-prefixes:
    - 2
    -
      excluded-identifiers:
        - 'webkit'
        - 'moz'
        - 'ms'
  no-warn: 2
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  id-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'hyphenatedlowercase'
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: 'camelcase'

  # Style Guide
  bem-depth: 0
  border-zero:
    - 2
    -
      convention: '0'
  brace-style:
    - 2
    -
      style: '1tbs'
      allow-single-line: false
  clean-import-paths: 0
  empty-args:
    - 2
    -
      include: true
  hex-length: 0
  hex-notation:
    - 2
    -
      style: 'lowercase'
  indentation:
    - 2
    -
      size: 'tab'
  leading-zero: 0
  nesting-depth: 0
  property-sort-order: 0
  quotes:
    - 2
    -
      style: 'double'
  shorthand-values: 0
  url-quotes: 0
  variable-for-property: 0
  zero-unit:
    - 2
    -
      include: false

  # Inner Spacing
  space-after-bang:
    - 2
    -
      include: false
  space-after-colon:
    - 2
    -
      include: true
  space-after-comma:
    - 2
    -
      include: true
  space-around-operator:
    - 2
    -
      include: true
  space-before-bang:
    - 2
    -
      include: true
  space-before-brace:
    - 2
    -
      include: true
  space-before-colon:
    - 2
    -
      include: false
  space-between-parens:
    - 2
    -
      include: false

  # Final Items
  final-newline:
    - 2
    -
      include: true
  trailing-semicolon:
    - 2
    -
      include: true
